---
# Пакеты для установки через pacman
pacman_packages:
  - reflector
  - flatpak
  - fwupd
  - git
  - base-devel
  - ffmpeg
  - gst-plugins-base
  - gst-plugins-good
  - gst-plugins-bad
  - gst-plugins-ugly
  - libva-mesa-driver
  - gst-libav
  - aom
  - dav1d
  - libwebp
  - flac
  - opus
  - libavif
  - libheif
  - libvpx
  - tmux
  - btop
  - vlc
  - wget
  - curl
  - duperemove
  - neovim
  - gamescope
  - lutris
  - steam
  - steam-devices 
  - gamemode
  - less
  - spotify-launcher
  - tuned
  - tuned-ppd
  - cups
  - splix
  - obs-studio
  - obsidian
  - pacman-contrib
  - tldr
  - gnome-firmware
  - bash-completion
  - seahorse
  - snapper
  - blanket
  - ptyxis
  - extension-manager
  - apparmor
  - grub-btrfs
  - inotify-tools
  - libva-mesa-driver
  - lib32-libva-mesa-driver
  - fish
  - dnsutils
  - iputils
  - whois
  - adobe-source-sans-fonts
  - adobe-source-serif-fonts
  - adobe-source-code-pro-fonts
  - noto-fonts-emoji
  - ttf-ubuntu-font-family
  - inter-font
  - ttf-liberation
  - ttf-dejavu
  - mangohud
  - nftables
  - firewalld
  - rustup
  - ripgrep
  - firewall-config
  - ttf-jetbrains-mono-nerd
  - npm

# Пакеты для установки через AUR (с помощью yay)
aur_packages:
  - btrfs-assistant
  - brave-bin
  - xdg-terminal-exec
  - visual-studio-code-bin
  - spotx-git
  - nautilus-open-in-ptyxis

# Пакеты для установки через Flatpak
flatpak_packages:
  - com.vysp3r.ProtonPlus
  - com.heroicgameslauncher.hgl

# Пакеты, которые нужно удалить
remove_packages:
  - firefox
  - htop
  - epiphany
  - totem
  - gnome-tour
  - snapshot
  - gnome-maps
  - rhythmbox
  - gnome-music
  - showtime
  - gnome-boxes
  - gnome-console
  - evolution
  - vim
  - vim-runtime
  - decibels
  - gnome-software

# Системные сервисы для включения и запуска
enable_services:
  - tuned
  - tuned-ppd
  - paccache.timer
  - firewalld
  - apparmor
  - grub-btrfsd

kde_lang:
  - { file: plasma-localerc, group: Language, key: Language, value: 'ru:en' }
  - { file: plasma-localerc, group: Formats, key: LANG, value: 'ru_RU.UTF-8'}
  - { file: kxkbrc, group: Layout, key: LayoutList, value: 'us,ru' }
  - { file: kxkbrc, group: Layout, key: Use, value: true }
  - { file: kxkbrc, group: Layout, key: VariantList, value: ','}
  - { file: kxkbrc, group: Layout, key: ResetOldOptions, value: true }
  - { file: kxkbrc, group: Layout, key: Options, value: 'kpdl:dotoss,grp:alt_shift_toggle,grp:win_space_toggle' }