---
dnf_packages:
  - tmux
  - btop
  - git
  - wget
  - curl
  - jetbrains-mono-fonts
  - rsms-inter-fonts
  - duperemove
  - btrfs-assistant
  - neovim
  - gamescope
  - lutris
  - steam
  - gamemode
  - gnome-tweaks
  - splix
  - tldr
  - vlc
  - libavcodec-freeworld
  - ffmpeg-libs
  - yaru-theme
  - xdg-terminal-exec
  - seahorse
  - fish
  - dnf-plugins-core
  - openssh-server
  - fwupd
  - flatpak
  - python3-pip
  - ffmpeg-free
  - mesa-va-drivers
  - mesa-vdpau-drivers

flatpak_packages:
  - com.heroicgameslauncher.hgl
  - com.vysp3r.ProtonPlus
  - com.mattjakeman.ExtensionManager
  - com.github.tchx84.Flatseal
  - md.obsidian.Obsidian
  - com.spotify.Client
  - com.rafaelmardojai.Blanket

remove_packages:
  - firefox*
  - libreoffice*
  - totem-video-thumbnailer
  - gnome-tour
  - gnome-maps
  - rhythmbox
  - gnome-music
  - yelp
  - showtime
  - gnome-contacts
  - gnome-boxes
  - snapshot
  - evolution
  - gnome-sound-recorder
  - shotwell
  - decibels

enable_services:
  - sshd

swap_packages:
  - { from: "mesa-va-drivers", to: "mesa-va-drivers-freeworld" }
  - { from: "mesa-va-drivers.i686", to: "mesa-va-drivers-freeworld.i686" }
  - { from: "mesa-vdpau-drivers", to: "mesa-vdpau-drivers-freeworld" }
  - { from: "mesa-vdpau-drivers.i686", to: "mesa-vdpau-drivers-freeworld.i686" }
  - { from: "ffmpeg-free", to: "ffmpeg" }
